name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - name: Build
        run: ./gradlew build sonarqube
        env:
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew publishPlugins
      - name: Tag version
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: ./gradlew tagVersion
